### ISSUE TITLE
HW explanation

### ISSUE THREAD

**Issue by darrepac** [sonic74/BLE-Bosch-CAN-Tongsheng-UART#1]
Hello

Can you detail more your HW setup?

thx

**Comment by sonic74** [comment]
I added a "Parts used" section to README.md
Are you interested in other details?

**Comment by darrepac** [comment]
Thanks
Ok so the processor is included within the CAN interface. What about BLE/ant+ transceiver??

**Comment by sonic74** [comment]
I first started using nRF52840 for ANT+, but then realized the ESP32's BLE is sufficient for transmitting cycling power/cadence to the Garmin.
ANT+ would have an eBike profile for battery stats though...

**Comment by darrepac** [comment]
oh didn’t see that Atom Lite has native BLE support… a good start indeed
Didn’t know that BLE didn’t have access to all messages (battery status for ex)

**Comment by sonic74** [comment]
It's about what profiles the Garmin can receive.

**Comment by sonic74** [comment]
I don't know an BLE equivalent to
https://www.thisisant.com/developer/ant-plus/device-profiles#527_tab
